---
- hosts: tag_Type_gateload
  remote_user: centos
  tasks:
  - name: go get gateload
    shell: GOPATH=/opt/go go get github.com/couchbaselabs/gateload
  - name: symlink gateload into /usr/local/bin
    file: src=/opt/go/bin/gateload dest=/usr/local/bin/gateload owner=centos group=centos state=link
    sudo: true
  - name: copy gateload config to host
    copy: src=files/gateload_config.json dest=/home/centos/gateload_config.json owner=centos group=centos mode=0644