---
- hosts: tag_CacheType_writer
  any_errors_fatal: true
  remote_user: centos
  sudo: true
  vars:
    writer: "true"
    couchbase_server_primary_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"
  tasks:
  - name: copy sync gateway config to host
    template: src=files/sync_gateway_config.json dest=/home/sync_gateway/sync_gateway.json owner=sync_gateway group=sync_gateway mode=0644 force=true
  - name: restart sync gateway service
    service: name=sync_gateway state=restarted
