---
- hosts: all
  connection: local
  tasks:
  - name: Create groups based on ec2 access key
    group_by: key=key_{{ ec2_key_name }}

- hosts: tag_Type_gateload
  vars:
    ec2keyname: andy_mac
  remote_user: centos
  sudo: yes

  tasks:

  - name: install git
    yum: pkg=git state=latest

  - name: install java
    yum: pkg=java-1.7.0-openjdk-devel

  - name: Create /opt directory
    file: path=/opt state=directory

  - name: Download Maven3
    get_url: dest=/opt/maven3.tar.gz url=http://apache.proserve.nl/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz

  - name: Unpack Maven3
    action: command creates=/opt/maven chdir=/opt tar zxvf /opt/maven3.tar.gz

  - name: Create Maven3 directory link
    file: path=/opt/maven src=/opt/apache-maven-3.2.5 state=link

  - name: Set mvn link
    action: command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1

  - name: Checkout sg-gatling load project from github
    git: repo=https://github.com/couchbaselabs/sg-gatling-load.git dest=/home/projects/sg-gatling-load force=yes

  - name: Remove somelog.txt before running theme
    file: path=/home/projects/sg-gatling-load/somelog.txt state=absent

  - name: Set sg-gatling-load baseURL for all themes
    lineinfile: dest=/home/projects/sg-gatling-load/pom.xml regexp='<simulation.targetHost>.*</simulation.targetHost>' line='<simulation.targetHost>{{ groups.tag_Type_syncgateway | intersect(groups.key_ec2keyname) | join(', ') }}</simulation.targetHost>'



