---
- hosts: tag_Type_syncgateway
  remote_user: centos
  sudo: true

  vars:
    couchbase_sync_gateway_centos_ee_version: 1.1.1
    couchbase_sync_gateway_centos_ee_package: couchbase-sync-gateway-centos_enterprise_{{ couchbase_sync_gateway_centos_ee_version }}-10_x86_64.tar.gz
    # TODO: Need this endpoint
    #couchbase_sync_gateway_centos_ee_url: http://XXXX{{ couchbase_sync_gateway_centos_ee_version }}/{{ couchbase_sync_gateway_centos_ee_package }}

  tasks:
  - debug: msg="Downloading sync_gateway v. {{ couchbase_sync_gateway_centos_ee_version }}"
  - name: Download sync_gateway
    get_url: url={{ couchbase_sync_gateway_centos_ee_url }} dest=/tmp/{{ couchbase_sync_gateway_centos_ee_package }}
  - name: Creates sync_gateway directory
    file: path=/home/centos/sync_gateway state=directory
  - name: Extract package
    unarchive: src=/tmp/{{ couchbase_sync_gateway_centos_ee_package }} dest=/home/centos/sync_gateway copy=no
