---
- hosts: tag_Type_syncgateway
  remote_user: centos
  sudo: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    # TODO: Need this endpoint
    couchbase_sync_gateway_package_url: {{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}

  tasks:
  - debug: msg="Downloading sync_gateway v. {{ couchbase_sync_gateway_package_url }}"
  - name: Download sync_gateway
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }}
  - name: Creates sync_gateway directory
    file: path=/home/centos/sync_gateway state=directory
  - name: Extract package
    unarchive: src=/tmp/{{ couchbase_sync_gateway_package }} dest=/home/centos/sync_gateway copy=no
