---
- hosts: tag_Type_couchbaseserver
  remote_user: centos
  serial: 1
  vars:
    couchbase_server_primary_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"

  connection: local
  tasks:

    - shell: echo {{couchbase_server_primary_node}} > ../../temp_couchbase_server_primary_node

- hosts: tag_Type_syncgateway
  remote_user: centos
  sudo: true
  vars:
    writer: "false"
  tasks:
  - name: set couchbase_server_primary_node variable
    set_fact:
      couchbase_server_primary_node: "{{ lookup('file', '../../temp_couchbase_server_primary_node') }}"
  - name: stop any sync gateway services that might be running
    service: name=sync_gateway state=stopped
  - name: add sync gateway user
    user: name=sync_gateway createhome=yes
  - name: make service install script executable
    file: path=/home/centos/sync_gateway/service/sync_gateway_service_install.sh mode=a+x
  - name: copy sync gateway binary to sync_gateway home
    shell: cp /home/centos/sync_gateway/bin/sync_gateway /home/sync_gateway
  - name: change permissions of sync gateway executable
    file: path=/home/sync_gateway/sync_gateway mode=a+x
  - name: copy sync gateway config to host
    template: src=files/sync_gateway_config.json dest=/home/sync_gateway/sync_gateway.json owner=sync_gateway group=sync_gateway mode=0644 force=true
  - name: install sync gateway service
    shell: ./sync_gateway_service_install.sh --sgpath=/home/sync_gateway/sync_gateway chdir=/home/centos/sync_gateway/service
  - name: wait until sync gateway to listen on port
    wait_for: port=4985 delay=1 timeout=30
  - name: disable sync gateway logging
    shell: curl -X PUT -d '{}' http://localhost:4985/_logging
