---
- hosts: tag_Type_couchbaseserver:tag_Type_syncgateway:tag_Type_gateload
  remote_user: centos
  sudo: true
  vars:
    splunkforwarder_package: splunkforwarder-6.2.2-255606-linux-2.6-x86_64.rpm
    splunkforwarder_url: http://www.splunk.com/page/download_track?file=6.2.2/universalforwarder/linux/{{ splunkforwarder_package }}&ac=adwords-syslog&wget=true&name=wget&platform=Linux&architecture=x86_64&version=6.2.2&product=splunk&typed=release
    forward_server: splunk.couchbasemobile.com:9997
    splunk_add_on_for_unix_and_linux: splunk-add-on-for-unix-and-linux_512.tgz
    splunk_add_on_for_unix_and_linux_url: http://couchbase-mobile.s3.amazonaws.com/perfcluster-aws/splunk_unix_linux_add_on/{{ splunk_add_on_for_unix_and_linux }}
    inputs_conf: /opt/splunkforwarder/etc/apps/Splunk_TA_nix/local/inputs.conf
  tasks:
  - name: kill splunkforwarder
    shell: pkill -9 splunk
    sudo: true
    ignore_errors: yes
  - name: uninstall splunkforwarder
    shell: rpm -e splunkforwarder && rm -rf /opt/splunkforwarder/
    sudo: true
    ignore_errors: yes
  - name: Download splunkforwarder
    get_url: url={{ splunkforwarder_url }} dest=/tmp/{{ splunkforwarder_package }}
  - name: install splunkforwarder
    shell: cd /tmp/ && sudo rpm -i {{ splunkforwarder_package }}
  - name: start splunkforwarder
    shell: /opt/splunkforwarder/bin/splunk start --accept-license
    sudo: true
  - name: add forward-server to Splunk forwarder
    shell: /opt/splunkforwarder/bin/splunk add forward-server {{ forward_server }} -auth admin:changeme
    sudo: true
  - name: Test the forwarder
    shell: /opt/splunkforwarder/bin/splunk list forward-server
    sudo: true

  - name: download 'Splunk Add-on for Unix and Linux'
    get_url: url={{ splunk_add_on_for_unix_and_linux_url }} dest=/tmp/{{ splunk_add_on_for_unix_and_linux }}
  - name: extract archive 'Splunk Add-on for Unix and Linux'
    shell: tar -C /opt/splunkforwarder/etc/apps/ -xvf /tmp/{{ splunk_add_on_for_unix_and_linux }}
  - name: copy Splunk Add-on for Unix and Linux' configs
    shell: mkdir /opt/splunkforwarder/etc/apps/Splunk_TA_nix/local && cp /opt/splunkforwarder/etc/apps/Splunk_TA_nix/default/inputs.conf {{ inputs_conf }}

  - name: enable vmstat in "inputs.conf"
    shell: sed -i ""$(($(awk '/vmstat\.sh./{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable iostat in "inputs.conf"
    shell: sed -i ""$(($(awk '/iostat\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable ps in "inputs.conf"
    shell: sed -i ""$(($(awk '/ps\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable top in "inputs.conf"
    shell: sed -i ""$(($(awk '/top\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable netstat in "inputs.conf"
    shell: sed -i ""$(($(awk '/netstat\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable cpu in "inputs.conf"
    shell: sed -i ""$(($(awk '/cpu\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: restart splunkforwarder
    shell: /opt/splunkforwarder/bin/splunk restart
    sudo: true


- hosts: tag_Type_syncgateway
  remote_user: centos
  sudo: true
  tasks:
  - name: Capture sync gateway logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /home/sync_gateway/logs -index main -sourcetype sync_gateway_logs  -auth admin:changeme
    sudo: true

- hosts: tag_Type_gateload
  remote_user: centos
  sudo: true
  tasks:
  - name: Capture gateload logs
    shell: mkdir -p /home/centos/logs && /opt/splunkforwarder/bin/splunk add monitor /home/centos/logs -index main -sourcetype sync_gateway_logs  -auth admin:changeme
    sudo: true

- hosts: tag_Type_couchbaseserver
  remote_user: centos
  sudo: true
  tasks:
  - name: Capture couchbase logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /opt/couchbase/var/lib/couchbase/logs -index main -sourcetype sync_gateway_logs  -auth admin:changeme
    sudo: true