---
- name: Download couchbase server
  get_url: url={{ couchbase_server_centos_ee_url }} dest=/tmp/{{ couchbase_server_centos_ee_package }}
- name: Install Couchbase Server
  yum: name=/tmp/{{ couchbase_server_centos_ee_package }} state=present
- name: Restart Couchbase Service
  service: name=couchbase-server.service state=restarted
- name: raise max file descriptors
  copy: src=files/security-nofiles-limit.conf dest=/etc/security/limits.d/20-nofiles.conf owner=root group=root mode=0644
- name: Disable Transparent Huge Pages
  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done' >> /etc/rc.local
  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done' >> /etc/rc.local
  shell: for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done