---
- hosts: tag_Type_syncgateway
  remote_user: centos
  sudo: true
  tasks:
  - name: clone sync gateway git repo
    git: repo=https://github.com/couchbase/sync_gateway.git
         dest=/home/centos/sync_gateway
         recursive=true
  - name: checkout feature branch
    shell: PATH=/usr/local/go/bin:/usr/bin:/usr/local/bin git checkout feature/distributed_cache chdir=/home/centos/sync_gateway
  - name: build sync gateway
    shell: PATH=/usr/local/go/bin:/usr/bin:/usr/local/bin ./build.sh chdir=/home/centos/sync_gateway
