---
- hosts: tag_Type_gateload
  remote_user: centos
  tasks:
  - name: kill gateload screen
    shell: screen -X -S gateload kill
  - name: kill gateload_expvars screen
    shell: screen -X -S gateload_expvars kill

    
