---
- hosts: tag_Type_couchbaseserver
  any_errors_fatal: true
  remote_user: centos
  sudo: true
  vars:
    couchbase_server_home_path: /opt/couchbase
    couchbase_server_bucket_name2: bucket-1
    couchbase_server_bucket_name3: bucket-2
    couchbase_server_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

  tasks:
  - name: set couchbase_server_primary_node variable
    set_fact:
      couchbase_server_primary_node: "{{ lookup('file', '../../temp_couchbase_server_primary_node') }}"
  - name: flush couchbase server bucket 1
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-flush --bucket={{ couchbase_server_bucket_name2 }} --force -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
    register: bucket_1_flush
  - debug: msg="{{ bucket_1_flush.stdout }}"
  - name: flush couchbase server bucket 2
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-flush --bucket={{ couchbase_server_bucket_name3 }} --force -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
    register: bucket_2_flush
  - debug: msg="{{ bucket_2_flush.stdout }}"

- hosts: tag_Type_syncgateway
  remote_user: centos
  sudo: true
  tasks:
  - name: stop sync_gateway service
    service: name=sync_gateway state=stopped
  - name: delete sync_gateway logs
    shell: rm -f /home/sync_gateway/logs/*.log
  - name: start sync_gateway service
    service: name=sync_gateway state=started
