---
- hosts: 127.0.0.1
  connection: local
  tasks:

   - name: test of local copy
     action: copy src=./files/cbagent_stats_monitor_template.spec dest=../../temp_cbagent_stats_monitor.spec


- hosts: tag_Type_syncgateway
  remote_user: centos
  serial: 1
  vars:
    couchbase_server_primary_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"

  connection: local
  tasks:
    - shell: a=`echo "  {{couchbase_server_primary_node}}"` && sed  -i "15 i\\$a" ../../temp_cbagent_stats_monitor.spec


- hosts: tag_Type_couchbaseserver
  serial: 1
  remote_user: centos
  vars:
    couchbase_server_primary_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"

  connection: local
  tasks:
    - shell: a=`echo "  {{couchbase_server_primary_node}}"` && sed  -i "3 i\\$a" ../../temp_cbagent_stats_monitor.spec


- hosts: tag_Type_gateload
  remote_user: centos
  vars:
    gateload_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"

  connection: local
  tasks:

    - shell: echo {{gateload_node}} > ../../temp_gateload_node



- hosts: tag_Type_couchbaseserver:tag_Type_syncgateway:tag_Type_gateload
  remote_user: centos
  sudo: true
  tasks:
  - name: install sysstat
    yum: pkg=sysstat state=latest


- hosts: tag_Type_gateload
  remote_user: centos
  sudo: true
  vars:
    gateload_node: "{{hostvars[ec2_public_dns_name]['ec2_private_dns_name']}}"
    primary_gateload_node: "{{ lookup('file', '../../temp_gateload_node') }}"
    key_name:  "{{ lookup('env','KEYNAME') }}"
  tasks:

  - name: copy ssh key to host
    template: src=~/.ssh/{{ key_name|regex_replace("^key_", '') }}.pem dest=/home/centos/.ssh/key.pem force=true
    when: primary_gateload_node == gateload_node

  - name: set ssh key into config file
    shell: echo "IdentityFile /home/centos/.ssh/key.pem" > /home/centos/.ssh/config && chmod 600 /home/centos/.ssh/config
    when: primary_gateload_node == gateload_node


  - name: Download splunkforwarder
    get_url: url=https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.1.tar.gz#md5=07e09df0adfca0b2d487e39a4bf2270a dest=/tmp/virtualenv-1.9.1.tar.gz
    when: primary_gateload_node == gateload_node

  - name: install Development Tools
    shell: yum groupinstall -y 'Development Tools'

  - name: install python-devel
    yum: pkg=python-devel state=latest

  - name: Download splunkforwarder
    get_url: url=http://packages.couchbase.com/rpm/couchbase-centos62-x86_64.repo dest=/etc/yum.repos.d/couchbase.repo
    when: primary_gateload_node == gateload_node

  - name: yum check-update
    shell: yum check-update
    when: primary_gateload_node == gateload_node
    ignore_errors: yes

  - name: install libcouchbase2-libevent libcouchbase-devel
    shell: sudo yum install -y libcouchbase2-libevent libcouchbase-devel --skip-broken
    when: primary_gateload_node == gateload_node

  - name: Download virtualenv
    get_url: url=https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.1.tar.gz#md5=07e09df0adfca0b2d487e39a4bf2270a dest=/tmp/virtualenv-1.9.1.tar.gz
    when: primary_gateload_node == gateload_node

  - name: Install virtualenv
    shell: "cd /tmp/ && tar -xvzf virtualenv-1.9.1.tar.gz && cd virtualenv-1.9.1 && python setup.py install"
    when: primary_gateload_node == gateload_node

  - name: Remove /home/centos/perfrunner
    shell: "rm -rf /home/centos/perfrunner"
    when: primary_gateload_node == gateload_node

  - name: Clone perfrunner into /home/centos/perfrunner
    git: repo=https://github.com/andreibaranouski/perfrunner
         dest=/home/centos/perfrunner
         force=yes
    when: primary_gateload_node == gateload_node

  - name: kill env.sh
    shell: pkill -f "env.sh"
    ignore_errors: yes
    when: primary_gateload_node == gateload_node

  - name: Run ./scripts/env.sh
    shell: "cd /home/centos/perfrunner; ./scripts/env.sh"
    when: primary_gateload_node == gateload_node

  - name: copy collect_url_requests.sh to host
    template: src=../../temp_cbagent_stats_monitor.spec dest=/home/centos/perfrunner/temp_cbagent_stats_monitor.spec force=true
    when: primary_gateload_node == gateload_node

  - name: kill workload.sh
    shell: pkill -f "workload.sh"
    ignore_errors: yes
    when: primary_gateload_node == gateload_node

  - name: Remove previous stats
    shell: "rm -rf /tmp/stats_folder/*"
    when: primary_gateload_node == gateload_node

  - name: Run ./scripts/workload.sh
    shell: "cd /home/centos/perfrunner && cluster=temp_cbagent_stats_monitor.spec test_config='tests/gateway_monitor.test' nohup ./scripts/workload.sh >/dev/null 2>&1 &"
    when: primary_gateload_node == gateload_node
















